# .rubocop-rails.yml

Rails/I18nLocaleTexts:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

Rails/UniqBeforePluck:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false